author = "panekj"
description = "C/C++ for Lapce: powered by clangd"
display-name = "C/C++ (clangd)"
name = "lapce-cpp-clangd"
wasm = "lapce-cpp-clangd.wasm"
version = "1.0.0"
icon = "logo.svg"
repository = "https://github.com/lapce-community/lapce-cpp-clangd"

[activation]
language = [
    "c",
    "cpp",
]

[config.clangdVersion]
default = "17.0.3"
description = "Version of clangd to automatically download"

[config.serverPath]
default = ""
description = "Path to clangd when not using automatic download"

[config.serverArgs]
default = "--background-index --clang-tidy --completion-style=detailed --fallback-style=LLVM --enable-config"
description = "Arguments passed to clangd server"

[config.cPattern]
default = "h,c"
description = "C file extensions passed to clangd server"

[config.cppPattern]
default = "H,hh,hpp,C,cc,cpp,c++"
description = "C++ file extensions passed to clangd server"
