author = "panekj"
description = "C/C++ for Lapce: powered by clangd"
display-name = "C/C++ (clangd)"
name = "lapce-cpp-clangd"
version = "1.0.0"
wasm = "bin/lapce-cpp-clangd.wasm"

[activation]
language = ["c", "cpp"]
workspace-contains = [
  "*/*.c",
  "*/*.h",
  "*/*.cpp",
  "*/*.hpp",
]

[config."volt.serverPath"]
default = ""
description = "Path to clangd"
